version: "3.9"

services:
  # [プロジェクトごとに設定]webアプリケーションのコンテナ
  sk_marche:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    # ports:
      # - 5173:5173  # 開発用vite（npm run dev）のポート
    env_file:
      - ./envs/_.env
      - ./envs/.env
      - ./../db_web_ssl/envs/db/_.env
      - ./../db_web_ssl/envs/db/.env

    volumes:
      - ./app/:/app/sk_marche

networks:
  default:
    name: db_web_ssl
    external: true
